name: Publish SQFluff PyPI Version

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ubuntu related dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libsasl2-dev unixodbc-dev python3-venv

      - name: Install python Dependencies
        run: |
          pip install --upgrade pip tox twine

      - name: Build Distribution (Core)
        run: tox -e build-dist

      - name: Publish Python distribution to PyPI
        env:
          TWINE_USERNAME: '${{ secrets.TWINE_USERNAME }}'
          TWINE_PASSWORD: '${{ secrets.TWINE_PASSWORD }}'
        run: |
          twine check dist/*
          twine upload dist/* --verbose
